// export const countries = [
//     { id: 1, name: "Afghanistan" },
//     { id: 2, name: "Albania" },
//     { id: 3, name: "Algeria" },
//     { id: 4, name: "Andorra" },
//     { id: 5, name: "Angola" },
//     { id: 6, name: "Antigua & Deps" },
//     { id: 7, name: "Argentina" },
//     { id: 8, name: "Armenia" },
//     { id: 9, name: "Australia" },
//     { id: 10, name: "Austria" },
//     { id: 11, name: "Azerbaijan" },
//     { id: 12, name: "Bahamas" },
//     { id: 13, name: "Bahrain" },
//     { id: 14, name: "Bangladesh" },
//     { id: 15, name: "Barbados" },
//     { id: 16, name: "Belarus" },
//     { id: 17, name: "Belgium" },
//     { id: 18, name: "Belize" },
//     { id: 19, name: "Benin" },
//     { id: 20, name: "Bhutan" },
//     { id: 21, name: "Bolivia" },
//     { id: 22, name: "Bosnia Herzegovina" },
//     { id: 23, name: "Botswana" },
//     { id: 24, name: "Brazil" },
//     { id: 25, name: "Brunei" },
//     { id: 26, name: "Bulgaria" },
//     { id: 27, name: "Burkina" },
//     { id: 28, name: "Burundi" },
//     { id: 29, name: "Cambodia" },
//     { id: 30, name: "Cameroon" },
//     { id: 31, name: "Canada" },
//     { id: 32, name: "Cape Verde" },
//     { id: 33, name: "Central African Rep" },
//     { id: 34, name: "Chad" },
//     { id: 35, name: "Chile" },
//     { id: 36, name: "China" },
//     { id: 37, name: "Colombia" },
//     { id: 38, name: "Comoros" },
//     { id: 39, name: "Congo" },
//     { id: 40, name: "Congo {Democratic Rep}" },
//     { id: 41, name: "Costa Rica" },
//     { id: 42, name: "Croatia" },
//     { id: 43, name: "Cuba" },
//     { id: 44, name: "Cyprus" },
//     { id: 45, name: "Czech Republic" },
//     { id: 46, name: "Denmark" },
//     { id: 47, name: "Djibouti" },
//     { id: 48, name: "Dominica" },
//     { id: 49, name: "Dominican Republic" },
//     { id: 50, name: "East Timor" },
//     { id: 51, name: "Ecuador" },
//     { id: 52, name: "Egypt" },
//     { id: 53, name: "El Salvador" },
//     { id: 54, name: "Equatorial Guinea" },
//     { id: 55, name: "Eritrea" },
//     { id: 56, name: "Estonia" },
//     { id: 57, name: "Ethiopia" },
//     { id: 58, name: "Fiji" },
//     { id: 59, name: "Finland" },
//     { id: 60, name: "France" },
//     { id: 61, name: "Gabon" },
//     { id: 62, name: "Gambia" },
//     { id: 63, name: "Georgia" },
//     { id: 64, name: "Germany" },
//     { id: 65, name: "Ghana" },
//     { id: 66, name: "Greece" },
//     { id: 67, name: "Grenada" },
//     { id: 68, name: "Guatemala" },
//     { id: 69, name: "Guinea" },
//     { id: 70, name: "Guinea-Bissau" },
//     {id: 71, name: "India"},
//     {id: 72, name: "Indonesia"},
//     {id: 73, name: 'Iran'}
// ]  

export const countries = [
    { id: 31, name: "Canada" },
    { id: 71, name: "India" }
]  